# Generated by Django 4.1 on 2022-11-01 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_remove_deliveries_unload_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_items',
            name='DLVRY_ITEM_TOTAL',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
