# Generated by Django 4.1 on 2022-11-01 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_orders_delvry_sts_alter_orders_ordr_no'),
        ('logistics', '0003_delivery_items_dlvry_item_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='DLVRY_COST',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='LOAD_COST',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='ORDR_ID',
            field=models.ForeignKey(db_column='ORDR_ID', on_delete=django.db.models.deletion.CASCADE, related_name='lg_ordr_id', to='inventory.orders'),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='RENT_COST',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery_items',
            name='ORDR_ITEM_ID',
            field=models.ForeignKey(db_column='ORDR_ITEM_ID', on_delete=django.db.models.deletion.CASCADE, to='inventory.order_items'),
        ),
        migrations.AlterField(
            model_name='delivery_items',
            name='PROD_QTY',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery_items',
            name='PROD_QTY_SQFT',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
