# Generated by Django 4.1 on 2022-11-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_alter_deliveries_dlvry_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveries',
            name='TOTL_DLVRY_ORDR_COST',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery_items',
            name='UNIT_PRICE_wDLVRY',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveries',
            name='DLVRY_COST',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='delivery_items',
            name='REC_ADD_BY',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery_items',
            name='REC_MOD_BY',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
