# Generated by Django 4.1 on 2022-11-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_remove_deliveries_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_items',
            name='UNIT_DLVRY',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery_items',
            name='UNIT_PRICE_noDLVRY',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
