# Generated by Django 4.1.2 on 2022-10-26 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('inventory', '0001_initial'),
        ('hrm', '0001_initial'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('CURNCY_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ISO_CODE', models.CharField(max_length=5)),
                ('SIGN', models.CharField(max_length=5)),
                ('COUNTRY', models.CharField(max_length=100)),
                ('CURENCY_NAME', models.CharField(blank=True, max_length=100, null=True)),
                ('COUNTRY_CODE_CNTRY_ABB', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'CURRENCY',
            },
        ),
        migrations.CreateModel(
            name='Expense_Transactions',
            fields=[
                ('EXPNS_TRANS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PAYMNT_DT', models.DateField(null=True)),
                ('PYMENT_TO', models.CharField(blank=True, max_length=100, null=True)),
                ('PYMNT_AMNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IS_CASH', models.IntegerField(default=0, null=True)),
                ('NOTES', models.CharField(blank=True, max_length=500, null=True)),
                ('TAX_PRCNT', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('TOTAL_noTAX', models.DecimalField(decimal_places=2, max_digits=10)),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField()),
                ('ACCT_ID', models.ForeignKey(db_column='ACCT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acct_id', to='accounts.accounts')),
                ('DLVRY_ID', models.ForeignKey(db_column='DLVRY_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.deliveries')),
                ('EXPNS_TYP_ACCT', models.ForeignKey(db_column='EXPNS_TYP_ACCT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expns_typ_acct', to='accounts.accounts')),
                ('PYMNT_BY_EMP_ID', models.ForeignKey(db_column='PYMNT_BY_EMP_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rn_salary_by_emp_id', to='hrm.employee')),
            ],
            options={
                'db_table': 'EXPENSE_TRANSACTIONS',
            },
        ),
        migrations.CreateModel(
            name='Expense_Transaction_Items',
            fields=[
                ('EXPNS_TRANS_ITEM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ITEM_NM', models.CharField(blank=True, max_length=45, null=True)),
                ('ITEM_DESC', models.CharField(blank=True, max_length=100, null=True)),
                ('ITEM_RATE_UNIT', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ITEM_UNIT_QUANTITY', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ITEM_TOTAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField()),
                ('EXPNS_TRANS_ID', models.ForeignKey(db_column='EXPNS_TRANS_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.expense_transactions')),
            ],
            options={
                'db_table': 'EXPENSE_TRANSACTION_ITEMS',
            },
        ),
        migrations.CreateModel(
            name='Earning_Transactions',
            fields=[
                ('EARN_TRANS_ID', models.AutoField(primary_key=True, serialize=False)),
                ('PYMNT_BY', models.CharField(blank=True, max_length=100, null=True)),
                ('PYMNT_AMNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PYMNT_DT', models.DateField(null=True)),
                ('IS_CASH', models.IntegerField(default=0, null=True)),
                ('NOTES', models.CharField(blank=True, max_length=300, null=True)),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField()),
                ('ACCT_ID', models.ForeignKey(db_column='ACCT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.accounts')),
                ('DLVRY_ID', models.ForeignKey(db_column='DLVRY_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.deliveries')),
                ('EMP_ID', models.ForeignKey(db_column='EMP_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee')),
                ('INVNTRY_TRANS_ID', models.ForeignKey(db_column='INVNTRY_TRANS_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory_transactions')),
            ],
            options={
                'db_table': 'EARNING_TRANSACTIONS',
            },
        ),
    ]
