# Generated by Django 4.1 on 2022-11-08 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cashledger_acct_ledger'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning_transactions',
            name='EARN_TYP_ACCT',
            field=models.ForeignKey(db_column='EARN_TYP_ACCT', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='earn_typ_acct', to='accounts.accounts'),
        ),
        migrations.AddField(
            model_name='expense_transactions',
            name='TOTAL_wTAX',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='Earning_Transaction_Items',
            fields=[
                ('EARN_TRANS_ITEM_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ITEM_DESC', models.CharField(blank=True, max_length=100, null=True)),
                ('ITEM_UNIT_AMNT', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ITEM_UNIT_QUANTITY', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('ITEM_TOTAL', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField()),
                ('EARN_TRANS_ID', models.ForeignKey(db_column='EXPNS_TRANS_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.earning_transactions')),
            ],
            options={
                'db_table': 'EARNING_TRANSACTION_ITEMS',
            },
        ),
    ]
