# Generated by Django 4.1 on 2022-11-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_earning_transactions_earn_typ_acct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning_transaction_items',
            name='EARN_TRANS_ID',
            field=models.ForeignKey(db_column='EARN_TRANS_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.earning_transactions'),
        ),
    ]
