# Generated by Django 4.1 on 2022-11-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_earning_transaction_items_rec_add_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_transaction_items',
            name='ITEM_DESC',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='expense_transaction_items',
            name='ITEM_NM',
            field=models.CharField(default=1, max_length=45),
        ),
    ]
