# Generated by Django 4.1 on 2022-11-18 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_expense_transaction_items_item_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_transaction_items',
            name='ITEM_DESC',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='expense_transaction_items',
            name='ITEM_NM',
            field=models.CharField(max_length=45),
        ),
    ]
