# Generated by Django 4.1 on 2022-11-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_expense_transaction_items_item_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning_transaction_items',
            name='ITEM_DESC',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='earning_transaction_items',
            name='ITEM_UNIT_AMNT',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='earning_transaction_items',
            name='ITEM_UNIT_QUANTITY',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
