# Generated by Django 4.1 on 2022-11-24 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_alter_earning_transactions_rec_add_by_and_more'),
        ('accounts', '0002_cashledger_acct_ledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_type',
            fields=[
                ('ACCT_TYPE_ID', models.AutoField(primary_key=True, serialize=False)),
                ('ACCT_TYPE_NM', models.CharField(max_length=45)),
                ('ACCT_TYPE_NM_UR', models.CharField(max_length=45, null=True)),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'account_type',
            },
        ),
        migrations.AddField(
            model_name='accounts',
            name='ACCT_DESC_UR',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ACCT_REF_UR',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='accounts',
            name='ACCT_TITLE_UR',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='ADDRESS_UR',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='POSTAL_CODE_UR',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='PROVINCE_UR',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='TEHSIL_UR',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='cashledger',
            name='EARN_TRANS_ID',
            field=models.ForeignKey(db_column='EARN_TRANS_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.earning_transactions'),
        ),
        migrations.AddField(
            model_name='cashledger',
            name='EXPNS_TRANS_ID',
            field=models.ForeignKey(db_column='EXPNS_TRANS_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.expense_transactions'),
        ),
        migrations.AddField(
            model_name='user',
            name='FIRST_NAME_UR',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='LAST_NAME_UR',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.CreateModel(
            name='acct_id_type_link',
            fields=[
                ('ACCT_ID_TYPE_LINK', models.AutoField(primary_key=True, serialize=False)),
                ('IS_ACTIVE', models.IntegerField(default=1)),
                ('ACCT_ID', models.ForeignKey(db_column='ACCT_ID', on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts')),
                ('ACCT_TYPE_ID', models.ForeignKey(db_column='ACCT_TYPE_ID', on_delete=django.db.models.deletion.CASCADE, to='accounts.account_type')),
            ],
            options={
                'db_table': 'acct_id_type_link',
            },
        ),
    ]
