# Generated by Django 4.1.2 on 2022-10-26 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EMP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_STRT_DT', models.DateTimeField()),
                ('EMP_TERM_DT', models.DateTimeField(blank=True, null=True)),
                ('EMP_STS', models.IntegerField(default=1)),
                ('EMP_TERM_REASN', models.CharField(blank=True, max_length=500, null=True)),
                ('CNIC', models.CharField(blank=True, max_length=45, null=True)),
                ('CNIC_EXP_DT', models.DateField(blank=True, null=True)),
                ('IS_ACTIVE', models.IntegerField(default=1)),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField()),
                ('REC_MOD_DT', models.DateTimeField(auto_now=True)),
                ('REC_MOD_BY', models.IntegerField()),
            ],
            options={
                'db_table': 'EMPLOYEES',
            },
        ),
        migrations.CreateModel(
            name='Employee_Departments',
            fields=[
                ('EMP_DEPT_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DEPT_NM', models.CharField(max_length=45)),
                ('DEPT_DESC', models.CharField(max_length=100, null=True)),
                ('IS_ACTIVE', models.IntegerField(default=1)),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField()),
                ('REC_MOD_DT', models.DateTimeField(auto_now=True)),
                ('REC_MOD_BY', models.IntegerField()),
            ],
            options={
                'db_table': 'EMPLOYEE_DEPARTMENTS',
            },
        ),
        migrations.CreateModel(
            name='Employment_Types',
            fields=[
                ('EMP_TYP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_TYP_NM', models.CharField(max_length=45)),
                ('EMP_TYP_DESC', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'EMPLOYMENT_TYPE',
            },
        ),
        migrations.CreateModel(
            name='Employee_Designations',
            fields=[
                ('EMP_DESIG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DESIG_NM', models.CharField(max_length=45)),
                ('DESIG_DESC', models.CharField(blank=True, max_length=100, null=True)),
                ('IS_ACTIVE', models.IntegerField(default=1)),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField()),
                ('REC_MOD_DT', models.DateTimeField(auto_now=True)),
                ('REC_MOD_BY', models.IntegerField()),
                ('EMP_DEPT_ID', models.ForeignKey(db_column='EMP_DEPT_ID', on_delete=django.db.models.deletion.CASCADE, to='hrm.employee_departments')),
            ],
            options={
                'db_table': 'EMPLOYEE_DESIGNATIONS',
            },
        ),
        migrations.CreateModel(
            name='Employee_Compensation',
            fields=[
                ('EMP_CMPNSTN_ID', models.AutoField(primary_key=True, serialize=False)),
                ('COMPNSTN_AMNT', models.DecimalField(decimal_places=2, max_digits=10)),
                ('COMPNSTN_UNIT', models.CharField(max_length=45)),
                ('EFFCT_STRT_DT', models.DateField(null=True)),
                ('EFFCT_END_DT', models.DateField(null=True)),
                ('PAY_FREQ_TYP', models.CharField(max_length=45)),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField(blank=True, null=True)),
                ('REC_MOD_DT', models.DateTimeField(auto_now=True)),
                ('REC_MOD_BY', models.IntegerField(blank=True, null=True)),
                ('EMP_ID', models.ForeignKey(db_column='EMP_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrm.employee')),
            ],
            options={
                'db_table': 'EMPLOYEE_COMPENSATION',
            },
        ),
        migrations.CreateModel(
            name='Employee_Attendance',
            fields=[
                ('EMP_ATTND_ID', models.AutoField(primary_key=True, serialize=False)),
                ('EMP_ATTND_DT', models.DateField()),
                ('EMP_ATTND_STS', models.IntegerField()),
                ('REC_ADD_DT', models.DateTimeField(auto_now_add=True)),
                ('REC_ADD_BY', models.IntegerField()),
                ('REC_MOD_DT', models.DateTimeField(auto_now=True)),
                ('REC_MOD_BY', models.IntegerField()),
                ('EMP_ID', models.ForeignKey(db_column='EMP_ID', on_delete=django.db.models.deletion.CASCADE, to='hrm.employee')),
            ],
            options={
                'db_table': 'EMPLOYEE_ATTENDANCE',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='EMP_DESIG_ID',
            field=models.ForeignKey(db_column='EMP_DESIG_ID', on_delete=django.db.models.deletion.CASCADE, to='hrm.employee_designations'),
        ),
        migrations.AddField(
            model_name='employee',
            name='EMP_TYP_ID',
            field=models.ForeignKey(db_column='EMP_TYP_ID', on_delete=django.db.models.deletion.CASCADE, to='hrm.employment_types'),
        ),
        migrations.AddField(
            model_name='employee',
            name='USER_ID',
            field=models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
