# Generated by Django 4.1 on 2022-10-22 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='DELVRY_STS',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='ORDR_NO',
            field=models.CharField(default=0, max_length=45),
        ),
    ]
